name: flutter_app
description: A new Flutter project to demonstrate skills.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  webview_flutter: ^4.10.10
  emoji_picker_flutter: ^4.4.0
  camera: 0.11.2+1
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.0     
  uuid: ^3.0.0
  provider: ^6.0.6
  webview_flutter_android: ^4.10.10


dev_dependencies:
  build_runner: any
  hive_generator: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#ffffff" 
  image: assets/logo.png 
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: scaleAspectFit


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png